### ISSUE TITLE
Examples fail with "ValueError: Unbound vertex attribute "gl_VertexID" at location 0"

### ISSUE THREAD

**Issue by akx** [szabolcsdombi/zengl#18]
Running on a Macbook Pro 2019, Python 3.9, macOS 10.15.7, the examples (tried a few) fail with

```
$ python julia_fractal.py
2022-06-02 21:03:34.519 Python[79599:798132] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Users/akx/build/zengl/examples/julia_fractal.py", line 14, in <module>
    scene = ctx.pipeline(
  File "/Users/akx/build/zengl/_zengl.py", line 382, in validate
    raise ValueError(f'Unbound vertex attribute "{name}" at location {location}')
ValueError: Unbound vertex attribute "gl_VertexID" at location 0
```
(please ignore the f string, I'm running #17 right now)

Is `gl_VertexID` supposed to be somehow implicitly bound by... something..?

Commenting out the check makes things work, but it sounds like there's something weird here :)

**Comment by szabolcsdombi** [comment]
I just realized the error message clearly says the location is 0 (not -1)

i added code to exclude the builtin variables by name

https://www.khronos.org/opengl/wiki/Built-in_Variable_(GLSL)#Vertex_shader_inputs
